name: drone-test
kind: pipeline

steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!!"

- name: setup go
  image: golang:1.15
  commands:
  - go version
  - go run sample.go
# https://docs.drone.io/pipeline/docker/examples/languages/golang/

- name: test
  image: docker/compose
  commands:
  - docker help
#  - docker-compose -f docker-compose-test.yml up -d

services:
- name: database
  image: mysql
  ports:
  - 3306
