name: drone-test
kind: pipeline

steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!!"

- name: setup go
  image: golang:1.15
  commands:
  - go run sample.go
  
services:
- name: database
  image: mysql
  ports:
  - 3306
