name: drone-test
kind: pipeline

steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!!"

- name: setup go
  image: golang:1.15
  commands:
  - go version
  - go run sample.go
# https://docs.drone.io/pipeline/docker/examples/languages/golang/

services:
- name: database
  image: mysql
  ports:
  - 3306
